import { 
  LayoutDashboard, 
  Zap, 
  Cpu, 
  Battery, 
  Sun, 
  Box, 
  Activity, 
  TrendingUp, 
  ShoppingCart, 
  BarChart3, 
  Bell, 
  PlayCircle, 
  FileText, 
  History, 
  Lightbulb, 
  BrainCircuit, 
  Map, 
  Users, 
  Settings, 
  ShieldCheck, 
  HelpCircle,
  Building2
} from 'lucide-react';

export const NAV_ITEMS = [
  { label: 'Dashboard', icon: LayoutDashboard, href: '/dashboard' },
  { label: 'Energy Overview', icon: Zap, href: '/energy-overview' },
  { label: 'Devices', icon: Cpu, href: '/devices' },
  { label: 'Batteries', icon: Battery, href: '/batteries' },
  { label: 'Solar Systems', icon: Sun, href: '/solar' },
  { label: 'Inverters', icon: Box, href: '/inverters' },
  { label: 'Grid Monitoring', icon: Activity, href: '/grid' },
  { type: 'separator', label: 'Trading & Market' },
  { label: 'Energy Trading', icon: TrendingUp, href: '/trading' },
  { label: 'Marketplace', icon: ShoppingCart, href: '/marketplace' },
  { label: 'Revenue Analytics', icon: BarChart3, href: '/revenue' },
  { type: 'separator', label: 'Monitoring' },
  { label: 'Telemetry', icon: History, href: '/telemetry' },
  { label: 'Alerts & Alarms', icon: Bell, href: '/alarms' },
  { label: 'Automation Rules', icon: PlayCircle, href: '/automation' },
  { type: 'separator', label: 'Insights' },
  { label: 'Reports', icon: FileText, href: '/reports' },
  { label: 'Historical Data', icon: History, href: '/history' },
  { label: 'Forecasting', icon: Lightbulb, href: '/forecasting' },
  { label: 'AI Insights', icon: BrainCircuit, href: '/ai-insights' },
  { type: 'separator', label: 'Management' },
  { label: 'Projects/Sites', icon: Building2, href: '/projects' },
  { label: 'Team Management', icon: Users, href: '/team' },
  { label: 'Settings', icon: Settings, href: '/settings' },
  { label: 'Audit Logs', icon: ShieldCheck, href: '/audit' },
  { label: 'Support Center', icon: HelpCircle, href: '/support' },
];
